dev:
  QUEUE_URL: 'https://sqs.us-east-1.amazonaws.com/637423183217/EventQ'
  DLQ_URL: 'https://sqs.us-east-1.amazonaws.com/637423183217/EventDLQ'
  TARGET_SYSTEM_API_URL: 'https://uat.concordnow.com/api/rest/1/organizations/1272/auto/'
  API_SECRET: /dev/apisecret

# uat:
  # QUEUE_URL: 'https://sqs.us-east-1.amazonaws.com/637423183217/EventQ'
  # DLQ_URL: 'https://sqs.us-east-1.amazonaws.com/637423183217/EventDLQ'
  # TARGET_SYSTEM_API_URL: 'https://uat.concordnow.com/api/rest/1/organizations/1272/auto/'
  # API_SECRET: /dev/apisecret

# prod:
  # QUEUE_URL: 'https://sqs.us-east-1.amazonaws.com/637423183217/EventQ'
  # DLQ_URL: 'https://sqs.us-east-1.amazonaws.com/637423183217/EventDLQ'
  # TARGET_SYSTEM_API_URL: 'https://uat.concordnow.com/api/rest/1/organizations/1272/auto/'
  # API_SECRET: /dev/apisecret
